### ISSUE TITLE
Añadir coordenadas manualmente

### ISSUE THREAD

**Issue by map10100** [xlx1004/GESPRO_PracticaGestionTareas_2021#12]

**Comment by xlx1004** [comment]
[Enter coordinates manually](https://github.com/davidmigloz/go-bees/commit/b15f3e86c3007d75a41ac3cb53db77ec9e79816b) #12

**Comment by xlx1004** [comment]
[Enter coordinates manually](https://github.com/davidmigloz/go-bees/commit/b15f3e86c3007d75a41ac3cb53db77ec9e79816b)#175
