### ISSUE TITLE
Diseñar poster

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#16]

**Comment by xlx1004** [comment]
[Add poster](https://github.com/davidmigloz/go-bees/commit/fb1b7041eb190ef2621ca5f639c571cb9ff929d2)#16

**Comment by xlx1004** [comment]
https://raw.githubusercontent.com/davidmigloz/go-bees/master/docs/latex/cartel.jpg

**Comment by xlx1004** [comment]
[Update poster](https://github.com/davidmigloz/go-bees/commit/fc0cae60bc3ccfaf132b3bedea656ce440042dca)#16
