### ISSUE TITLE
Crear página web

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#17]

**Comment by xlx1004** [comment]
https://startbootstrap.com/template-overviews/new-age/
http://www.grabon.in/mobile-apps/

http://bronto.github.io/javasphinx/

**Comment by xlx1004** [comment]
[Add Google Play link](https://github.com/davidmigloz/go-bees/commit/5dfc67ae6470435977dc312f71a0f5db714b8523) #17

**Comment by xlx1004** [comment]
[Update .gitignore](https://github.com/davidmigloz/go-bees/commit/bced5cf90dc7bc5643091fd764b250bd3608e833)  #17

**Comment by xlx1004** [comment]
[Finish website](https://github.com/davidmigloz/go-bees/commit/d1416a50a7fa680231fb8d31cd0a44dd293354af)   #17

**Comment by xlx1004** [comment]
[Minor fixes and compress imgs](https://github.com/davidmigloz/go-bees/commit/2f02db902e1bc149e88d8a2de6e3254b33ffb79a) #17

**Comment by xlx1004** [comment]
[Minor changes](https://github.com/davidmigloz/go-bees/commit/270d4d4e862e9f0f5cd9fa18defe1af543f88c3c) #17

**Comment by xlx1004** [comment]
[Minor changes](https://github.com/davidmigloz/go-bees/commit/d473fe0fa52a58680c0b5dd81d43c16085689647)  #17

**Comment by xlx1004** [comment]
[Add docs link](https://github.com/davidmigloz/go-bees/commit/07a31d8f5a07583ce012782b65e0b46816dedc68)  #17

**Comment by xlx1004** [comment]
http://gobees.io/
