### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#19]

**Comment by xlx1004** [comment]
- Código fuente app
- Ejecutable app
- Herramientas

   - Plataforma de desarrollo del algoritmo
   - Herramienta de conteo de abejas

- Documentación

   - Memoria
   - Anexos
   - JavaDoc
- Dataset de videos

**README**

- Repositorio GoBees
- Repositorio prototipos
- Repositorio dependencia OpenCV

**Comment by xlx1004** [comment]
[Add cd cover](https://github.com/davidmigloz/go-bees/commit/0d85bcab1200e43e15378314ffbeb205e47bd151)  #19

**Comment by xlx1004** [comment]
[Add cd cover](https://github.com/davidmigloz/go-bees/commit/417cb723ed991ef695fbfc07ff3364bb1d409842)  #19
