### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by map10100** [xlx1004/GESPRO_PracticaGestionTareas_2021#20]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by ghost** [comment]
![d516b7cc-e74c-11e6-8cba-fbaf3b625cde](https://user-images.githubusercontent.com/74242933/100548986-82f8c700-3270-11eb-9cdf-77825d9b9e74.jpg)
![d51c4822-e74c-11e6-8824-8f740999d7a6](https://user-images.githubusercontent.com/74242933/100549036-db2fc900-3270-11eb-96ff-8893eda21d32.jpg)
![d51cffec-e74c-11e6-8b8e-3d1a257863ca](https://user-images.githubusercontent.com/74242933/100549042-e1be4080-3270-11eb-8237-bc408e170631.jpg)
![d51eeadc-e74c-11e6-8c9f-b4e07db90505](https://user-images.githubusercontent.com/74242933/100549049-eedb2f80-3270-11eb-97c2-83fd1afae1c8.jpg)
![d516e42c-e74c-11e6-9572-0cd8f7839c07](https://user-images.githubusercontent.com/74242933/100549052-f4387a00-3270-11eb-9e89-4cb03337450d.jpg)
![d51733c8-e74c-11e6-9426-02d792871fca](https://user-images.githubusercontent.com/74242933/100549056-f8fd2e00-3270-11eb-9702-1175ac260c87.jpg)

**Comment by xmv1001** [comment]
![d51c4822-e74c-11e6-8824-8f740999d7a6](https://user-images.githubusercontent.com/74242933/100549011-b76c8300-3270-11eb-9a3b-63192f6bdcfb.jpg)

**Comment by ghost** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
