### ISSUE TITLE
Valores de los ejes incorrectos en los gráficos del tiempo

### ISSUE THREAD

**Issue by map10100** [xlx1004/GESPRO_PracticaGestionTareas_2021#24]
Las leyendas no se corresponden con los valores reales en los gráficos de temperatura, lluvia y viento en la vista grabación.

**Comment by jms1008** [comment]
[Fix weather charts](https://github.com/davidmigloz/go-bees/commit/0739dbca057a7eddf49d1339364149c40bb0e0c4) #24
