### ISSUE TITLE
Rematar memoria

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#26]
- [x]  Enlace Google Play.
- [x]  Imagen CI
- [x]  Tabla de estadísticas
- [x]  Firmar electrónicamente
- [x]  Imagen página web o google play

**Comment by xlx1004** [comment]
[Improve docs](https://github.com/davidmigloz/go-bees/commit/c6af4abca3e563d6ebb45c04c5d57ea86116dbdf) #26
