### ISSUE TITLE
Imprimir memoria

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#28]

**Comment by xlx1004** [comment]
La memoria ha de estar encuadernada en formato:

- Libro cosido,
- Libro pegado,
- Libro con grapa de canto metálico prensada.
- Revista de tapa dura y grapa.

No se deben usar formatos de encuadernación de tornillos, espirales, canutillos y similares.

**Comment by xlx1004** [comment]
[Finish report](https://github.com/davidmigloz/go-bees/commit/bcc53af23527b7650fa9333205cb9fc9f9ef7cac) #28
