### ISSUE TITLE
Menú lateral

### ISSUE THREAD

**Issue by jms1008** [xlx1004/GESPRO_PracticaGestionTareas_2021#3]
- Settings
- **Help**
- Send feedback
- Share this app
- **About**

https://github.com/mikepenz/AboutLibraries

**Comment by jms1008** [comment]
Settings
Help
Send feedback
Share this app
About
https://github.com/mikepenz/AboutLibraries

**Comment by ghost** [comment]
![e2db27f0-db74-11e6-98f0-c9a4857bfb5c](https://user-images.githubusercontent.com/74242933/100548881-cacb1e80-326f-11eb-9af7-78ac314b5b47.jpeg)

**Comment by ghost** [comment]
[Implement about section](https://github.com/davidmigloz/go-bees/commit/cb2d0d7f17a319be12976eb4f92b26a295b500b2) #3

**Comment by ghost** [comment]
[Implement help section](https://github.com/davidmigloz/go-bees/commit/a92336cea00156c3df7425b874f29e095fa95830) #3
