### ISSUE TITLE
Pasar memoria doc a latex

### ISSUE THREAD

**Issue by map10100** [xlx1004/GESPRO_PracticaGestionTareas_2021#31]
- Revisar imágenes.
- Revisar bibliografía.
- bibentry (http://gking.harvard.edu/files/bibentry2.pdf).

### Documentación

  

- [x] Resumen
- [x]   Introducción
- [x]   Objetivos del proyecto
- [x]   Conceptos teóricos
- [x]   Técnicas y herramientas
- [x]   Aspectos relevantes
- [x]   Trabajos relacionados
- [x]   Conclusiones y Líneas de trabajo futuras

**Comment by ghost** [comment]
Expresión regular para corregir las referencias:

- Buscar: `(\{\[\})([\w:\\]+)(\{\]\}\\\_)`
- Reemplazar por: `\\citep{\2}`
Ej: `{[}art:campbell2005{]}\_ -> \citep{art:campbell2005}`

***

Expresión regular para corregir las imágenes:

- Buscar: `(\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})`
- Reemplazar por:` \\imagen{\2}{descripción...}`
Ej: `\includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}`

**Comment by ghost** [comment]
### Cheat-sheet plantilla

#### Rutas de ficheros / paquetes

`\ruta{C:/Windows/System32}`

#### Imágenes

Imagen en el sitio introducido:

`\imagen{nombre-img}{Descripción...}`

Imagen flotante:

`\imagenflotante{nombre-img}{Descripción...}`

> El nombre de la imagen sin extensión

**Comment by ghost** [comment]
[Convert to latex points 1 and 2](https://github.com/davidmigloz/go-bees/commit/e34ee575fc16f309312fb5d927bda29c756b52f7) #31

**Comment by ghost** [comment]
[Convert to latex point 3](https://github.com/davidmigloz/go-bees/commit/a8f439db8c247e9fb6c8506732ffbed688bebfa7) #31

**Comment by ghost** [comment]
[Convert to latex point 4](https://github.com/davidmigloz/go-bees/commit/9e96b3cc1316702e295429576081ac054e994c48) #31

**Comment by ghost** [comment]
[Convert to latex point 5](https://github.com/davidmigloz/go-bees/commit/937d88847c3795b35fe5b62fdb860cf9f1c75f2b) #31

**Comment by ghost** [comment]
[Convert to latex point 6](https://github.com/davidmigloz/go-bees/commit/4fe15ad8f24552ab93fd13c383f2348c7ad09ca0) #31

**Comment by ghost** [comment]
[Convert to latex point 7](https://github.com/davidmigloz/go-bees/commit/1f185fd412a35a8fed4f08fa578bbdebbdea64ae) #31

**Comment by ghost** [comment]
[Improve references](https://github.com/davidmigloz/go-bees/commit/8f33e4557a4d5b48ab15104e6ea9f0756c93c165) #31
