### ISSUE TITLE
Manual del programador

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#32]

**Comment by xlx1004** [comment]
- Instalación Android Studio
- Importación del proyecto
- Estructura directorios
- Ejecución tests en local
- Servicios de integración continua
- Creación de un ejecutable
- Plataforma de desarrollo del algoritmo
- Plataforma de conteo

**Comment by xlx1004** [comment]
[Add javadoc](https://github.com/davidmigloz/go-bees/commit/674177f869d071c56047ff6656f16dab03cbf2d2) #32

**Comment by xlx1004** [comment]
[Document Manual Programador](https://github.com/davidmigloz/go-bees/commit/368ab1a32862ebfdbdd815ad8701fdb76bb3e487) #32

**Comment by xlx1004** [comment]
[Convert annex C to latex](https://github.com/davidmigloz/go-bees/commit/af309e0a79b91031c3e8286af3818350c7133726) #32
