### ISSUE TITLE
Pasar anexos a latex

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#33]

**Comment by xlx1004** [comment]
**Anexos**

- [ ]  Plan del proyecto software
- [ ]  Especificación de Requisitos
- [ ]  Especificación de diseño
- [ ]  Manual del programador
- [ ]  Manual de usuario

Expresión regular para corregir las referencias:

- Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
- Reemplazar por: \\citep{\2}

Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

Expresión regular para corregir las imágenes:

- Buscar: (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})
- Reemplazar por: \\imagen{\2}{descripción...}

Ej: \includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}

**Comment by xlx1004** [comment]
[Convert annex D to latex](https://github.com/davidmigloz/go-bees/commit/922e3d0edc61fb90198e46ed5feee9c6e4c5643e) #33

**Comment by xlx1004** [comment]
[Convert annex E to latex](https://github.com/davidmigloz/go-bees/commit/6191452efdca08618b6f9bf7ea75a8416c686ed7) #33

**Comment by xlx1004** [comment]
[Convert annex B to latex](https://github.com/davidmigloz/go-bees/commit/613187d1c98664dc7a8dfff65ed727d71a6b92f2) #33

**Comment by xlx1004** [comment]
[Convert annex A to latex](https://github.com/davidmigloz/go-bees/commit/d34aafacf17b2c9e9cf85e101e48c6991520371d) #33
