### ISSUE TITLE
Diseño arquitectónico

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#37]

**Comment by xlx1004** [comment]
[Document Diseno Arquitectonico](https://github.com/davidmigloz/go-bees/commit/c3dbf4c80fe6e0d13214ae1ea40dc87fc197a072) #37

**Comment by xlx1004** [comment]
[Add references](https://github.com/davidmigloz/go-bees/commit/7225b05a4fb9dbcd380f6cd654b34dfcb0cd8963) #37

**Comment by xlx1004** [comment]
[Improve Diseno Arquitectonico documentation](https://github.com/davidmigloz/go-bees/commit/7f1d2380f49f07ec9c7c0e92372ec904a521919d) #37
