### ISSUE TITLE
Internacionalizar app

### ISSUE THREAD

**Issue by jms1008** [xlx1004/GESPRO_PracticaGestionTareas_2021#4]

**Comment by jms1008** [comment]
Idiomas disponibles:

Español
Inglés
Catalán
Polaco
Árabe
En proceso:

Alemán
Frances

**Comment by map10100** [comment]
[Localize Catalan](https://github.com/davidmigloz/go-bees/commit/9b4c4247fc5ef0dc893381fd1f2b6e4268431724) #4

**Comment by map10100** [comment]
[Localize Arabic](https://github.com/davidmigloz/go-bees/commit/9b4c4247fc5ef0dc893381fd1f2b6e4268431724) #4

**Comment by map10100** [comment]
[Localize Spanish](https://github.com/davidmigloz/go-bees/commit/9b4c4247fc5ef0dc893381fd1f2b6e4268431724) #4

**Comment by map10100** [comment]
Idiomas disponibles:

- Español
- Inglés
- Catalán
- Polaco
- Árabe

En proceso:

- Alemán
- Frances

**Comment by map10100** [comment]
[Localize Polish](https://github.com/davidmigloz/go-bees/commit/433c1a6a29bd3e8a9cc481447626a3f09ed0609e) #4
