### ISSUE TITLE
Las imágenes no se posicionan correctamente en el pdf autogenerado

### ISSUE THREAD

**Issue by ghost** [xlx1004/GESPRO_PracticaGestionTareas_2021#46]

**Comment by jms1008** [comment]
http://stackoverflow.com/questions/24285445/sphinx-to-latex-figure-placement

**Comment by jms1008** [comment]
[Fix pdf images position](https://github.com/davidmigloz/go-bees/commit/b5d991f79ade4a15414533466e1f0695eb381aca)#46

**Comment by jms1008** [comment]
[Fix images position](https://github.com/davidmigloz/go-bees/commit/271284b37d1c4fbcf8abe6121fbd7e1f03017aca) #46

**Comment by jms1008** [comment]
[Fix images position](https://github.com/davidmigloz/go-bees/commit/844ae5227dd5be359470b35e4b8aaf231d47a907) #46

**Comment by jms1008** [comment]
[Fix images position](https://github.com/davidmigloz/go-bees/commit/5255bc844c912768627b695ff6055bfeb289225c) #46

**Comment by map10100** [comment]
[Fix images position](https://github.com/davidmigloz/go-bees/commit/5255bc844c912768627b695ff6055bfeb289225c) #46

**Comment by map10100** [comment]
[Fix images position](https://github.com/davidmigloz/go-bees/commit/5255bc844c912768627b695ff6055bfeb289225c) #46

**Comment by map10100** [comment]
[Fix images position](https://github.com/davidmigloz/go-bees/commit/5255bc844c912768627b695ff6055bfeb289225c) #46

**Comment by map10100** [comment]
[Fix images position](https://github.com/davidmigloz/go-bees/commit/5255bc844c912768627b695ff6055bfeb289225c) #46
