### ISSUE TITLE
Implementar splash screen

### ISSUE THREAD

**Issue by map10100** [xlx1004/GESPRO_PracticaGestionTareas_2021#47]
En vez de dejar en blanco la pantalla mientras carga la app, mostrar una pantalla con el logo de la app.
https://www.bignerdranch.com/blog/splash-screens-the-right-way/
https://material.io/guidelines/patterns/launch-screens.html

**Comment by jms1008** [comment]
[Add splash activity](https://github.com/davidmigloz/go-bees/commit/67aed85b8c96b5b37bd2c5b2fc90c4c60cc99c13) #47
