### ISSUE TITLE
Integración de SonarQube

### ISSUE THREAD

**Issue by map10100** [xlx1004/GESPRO_PracticaGestionTareas_2021#49]
Aunque ya se cuenta con code climate y codecov entre los servicios de integración continua para evaluar la calidad del código, sería recomendable pasar también los motores de análisis de SonarQube ya que es el que utilizará el tribunal para evaluar el TFG.

https://sonarqube.com/
https://github.com/integrations/sonarqube
https://docs.travis-ci.com/user/sonarqube/

**Comment by jms1008** [comment]
[Integrate SonarQube](https://github.com/davidmigloz/go-bees/commit/6c7b49614e012e8edb6340d2aad7ba171fe096dc) #49

**Comment by jms1008** [comment]
[ Minor fix SonarQube](https://github.com/davidmigloz/go-bees/commit/249496d26dbf4b8ed2fb335898996932bc12ac2f) #49

**Comment by jms1008** [comment]
[Minor fixes](https://github.com/davidmigloz/go-bees/commit/e7b51c8bf3e1967b10571b241c0ccbdb3e1c279b) #49

**Comment by jms1008** [comment]
[Minor fixes](https://github.com/davidmigloz/go-bees/commit/890615215b85b8160bb5e5b76db8160fee9b1294) #49

**Comment by jms1008** [comment]
[Finish SonarQube integration](https://github.com/davidmigloz/go-bees/commit/a9319af96999de073b618812727859ed0b9c6a57) #49

**Comment by ghost** [comment]
[Add coverage report to sonarqube](https://github.com/davidmigloz/go-bees/commit/7fb5bedf949343be53877f0bf44dbfa3c63e0416) #49

**Comment by ghost** [comment]
[Fix exclusions sonarqube](https://github.com/davidmigloz/go-bees/commit/053a87fd71d9f905e6ae8c4bcf5f19549cff2df8) #49

**Comment by ghost** [comment]
[Fix exclusions sonarqube](https://github.com/davidmigloz/go-bees/commit/885259655886650d6f31d5c9285d4efa9f04563f) #49

**Comment by ghost** [comment]
[Fix binary files sonarqube](https://github.com/davidmigloz/go-bees/commit/f66e928286428e0aab52475630e36a1b0db687ac) #49
