### ISSUE TITLE
Actualizar a OpenCV 3.2

### ISSUE THREAD

**Issue by jms1008** [xlx1004/GESPRO_PracticaGestionTareas_2021#6]

**Comment by jms1008** [comment]
https://github.com/xlx1004/GESPRO_PracticaGestionTareas_2021/issues/6

**Comment by jms1008** [comment]
Tras actualizar dependencia a la nueva versión OpenCV 3.2 y probar la app, se ha visto que han corregido el bug que tenía OpenCV Manager con la versión anterior (#26).

**Comment by map10100** [comment]
[Update OpenCV 3.3](https://github.com/davidmigloz/go-bees/commit/1190b0293a466f88af461258cbf2c9cecaf2618e) #6
