### ISSUE TITLE
Actualizar Técnicas y Herramientas

### ISSUE THREAD

**Issue by jms1008** [xlx1004/GESPRO_PracticaGestionTareas_2021#8]
Gradle / Maven
 JavaFx
 Patrones: Repository, ViewHolder, Builder, Singleton
 Android
 Realm
 Jacabo / VNTNumberPickerPreference / Permission Utils
 Google Play Services
 MPAndroidChart-
 reStructuredText / Sphinx
 Github Pages
 OpenWeatherMaps
 https://translate.google.com/toolkit
 Material Design

**Comment by map10100** [comment]
[Update Tecnicas y Herramientas](https://github.com/davidmigloz/go-bees/commit/caab7b7e0a01ac7a20ce5538df32689a38c0d4a9) #8
