### ISSUE TITLE
Documentar Aspectos relevantes

### ISSUE THREAD

**Issue by jms1008** [xlx1004/GESPRO_PracticaGestionTareas_2021#9]
**Inicio del proyecto:**

- Introducción

**Metodologías**

- Ensayo / error
- TDD

**Formación:**

- OpenCV
- Android

**Desarrollo del algoritmo:**

- Búsqueda bibliográfica
- Plataforma de desarrollo

**Desarrollo de la app:**

- Prototipos
- Bugs
- MVP
- Material design
- Patrones
- Servicio de monitorización
- OpenWeatherMap API
- Internacionalización

**Testing:**

- Integración continua
- Algoritmo
- Métricas de calidad
- Estadísticas del proyecto

**Documentación:**

- Documentación continua
- GitHub Pages - ReadTheDocs
- Markdown - RST

**Publicación:**

- Google Play
- Web

**Reconocimientos:**

- Beca prototipo
- Beca de colaboración
- Yuzz

**Comment by ghost** [comment]
[Document Aspectos Relevantes](https://github.com/davidmigloz/go-bees/commit/a98876e2fc26b4f607f7da2daf7320282b517948) #9

**Comment by ghost** [comment]
[Update Aspectos Relevantes](https://github.com/davidmigloz/go-bees/commit/77782c121b541db94a8ce4bbe782ab046436a285) #9

**Comment by ghost** [comment]
[Minor change Aspectos Relevantes](https://github.com/davidmigloz/go-bees/commit/db0f9573d5656d32b49a9f5a104a78198a3bb5e3) #9
